### ISSUE TITLE
New Business Goal is placed. 

### ISSUE THREAD

**Issue by jose598** [luisabrie/ISII-WORKSHOPS-TELEMERCADEO#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group,  we proposed some changes with the intention of improving our service and getting more customers.
The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our requirement should be added to the existing one and the result should be calculated with all rules applied.

**Comment by APAZ10** [comment]
We will proceed to process the request, @lefreire99 will be the assigned analyst, @luisabrie will develop the solution and @APAZ10 will perform the tests.

**Comment by APAZ10** [comment]
We verified that the requirement has not been implemented and we will address it.

**Comment by APAZ10** [comment]
We analyzed the request and we categorized it as an enhancement.

**Comment by lefreire99** [comment]
@jose598 please check our impact analysis report.
[Impact Analysis.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7900975/Impact.Analysis.docx)

**Comment by jose598** [comment]
Hi @lefreire99 . I don't accept your analysis report for these reasons.
For me like a customer of this software, all changes are important even when the change can be solved during 5 mins or you don't use our hardware. So, please - No say that (In your future like a software developer, you can't say a customer what she/he wants will be solved with insignificant impact, whatever changes even when the issue is small but for the customer is essential) .
Sideway, I'd like to take a look at how you are calculating the insurance cost result, so please send me the attached document with a table with all cases/rules applied for getting the result and please send me a cost/times that you will use for getting this issue.
What's the end of the day for you? it means hours. 



Thank you.

**Comment by lefreire99** [comment]
Hi @jose598 please check again our analysis report, we have made some changes to it.
Thank you.
[Impact Analysis.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7901841/Impact.Analysis.docx)

**Comment by jose598** [comment]
Why a minimal changes like you said cost $35 for each one? Can you explain it, please? 
It's a little difficult to understand how your are calculating, maybe in the test process I will notice better. For now, please check that the first request that you wrote on the second table, the discount is $100, no $50 because the discount is for the couple, it means $50 less for each one.

**Comment by lefreire99** [comment]
In base of your last comment, we have made some changes to the analysis report, specifically, explaining the cost of each requirement. Please let us know any other consideration. 
Thank you.
[Impact Analysis.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7901991/Impact.Analysis.docx)

**Comment by jose598** [comment]
Well, I think is so expensive considering the insignificant impact that this issue will be it. 
All you can start working on this issue.

**Comment by luisabrie** [comment]
Based on request #1, version 4.0 of the code has been uploaded to the IssueManagement branch, it address your proposed changes.
For requirement 1 we have done the following changes:
https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/blob/7719715f0a4d5452a570de8f9dc8fec1517b2db6/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Insurance.java#L35-L38
For requirement 2 we have done the following changes:
https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/blob/7719715f0a4d5452a570de8f9dc8fec1517b2db6/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/FemaleInsurance.java#L10-L13

**Comment by APAZ10** [comment]
Attached is the test plan and the corresponding results.  
[Test plan with Path Coverage.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7902917/Test.plan.with.Path.Coverage.docx)
s

**Comment by APAZ10** [comment]
Attached is the acceptance test plan, please @jose598 review it and let us know if you agree.
[Acceptance Testing.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7903046/Acceptance.Testing.docx)

**Comment by luisabrie** [comment]
Hi @jose598. Hope this message finds you well.
It has been more than 48 hours since our last interaction, if we do not receive a response by 19:00 GMT-5, we will mark the solution as accepted, close the issue and proceed to issue the invoice.
Best regards,
Luis

**Comment by jose598** [comment]
Recently I got a notification for this group. 
I have more than 20 groups on the same time, if you don't tag me I never look this one. 
You can close the issue, but the issue is not solved for the customer.

**Comment by APAZ10** [comment]
> Attached is the acceptance test plan, please @jose598 review it and let us know if you agree. [Acceptance Testing.docx](https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO/files/7903046/Acceptance.Testing.docx)

We did tag you 2 days ago, and we have also sent several messages through Teams on these days in order for you to verify the acceptance test plan. @jose598

**Comment by jose598** [comment]
@APAZ10 Yes, and already responded when your tag, when you didn't tag and responded as well, but since yesterday I already have more than 20 group trying to solve the issue. 

According with your test plan, I didn't see test cases about the two minimal cases(like you said). Change this one please, of course if you will work on this issue.

**Comment by APAZ10** [comment]
Test cases 1,2,3,4,5,6 apply to the first requirement and the test cases 3,4,5 and 6 apply to the second requirement. @jose598

**Comment by lefreire99** [comment]
The client said that the issue has been resolved so @luisabrie will procced to release the new version of the software.

**Comment by luisabrie** [comment]
Ok, @lefreire99 and @APAZ10. We will proceed to release version 4.0 of the software that @jose598 proposed. To run it, the following steps must be performed:

1. Verify that a version high or equal to Java 11 is installed at your machine.
2. Verify that you have git installed at your machine.
3. Verify that Eclipse is installed at your machine
3. Clone the project from the Issue Management branch. To do that you have to run the following command on the terminal. `git clone --branch IssueManagement https://github.com/luisabrie/ISII-WORKSHOPS-TELEMERCADEO.git`
4. Since the application is not ready to distribute as a JAR file, import the project to Eclipse and run it like previous projects.
5. The CLI interface has not change since past version, so you would interact with it in the same way.

**Comment by APAZ10** [comment]
@jose598 Please let us know that you were able to use the software, and if the answer is positive, tell us if you are satisfied with the solution.

**Comment by jose598** [comment]
Yes, I already did. 
Thank you @APAZ10
